# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u964d\u9f99\u5341\u516b\u638c', max_length=50, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
