# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20171103_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5e7f\u544a\u56fe'),
        ),
    ]
